spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/address #jdbc:oracle:thin:@//192.168.0.184:1521/DBNEW
    username: admin #asbt
    password: password123 #asbt32
    driver-class-name: org.postgresql.Driver #oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 8
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect #org.hibernate.dialect.Oracle9iDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      temp:
        use_jdbc_metadata_defaults: false
      jdbc:
        time_zone: Asia/Tashkent
server:
  port: 8081